# Generated by Django 3.2.8 on 2021-11-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1500)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=200)),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
